// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCW7TDgcMjpnWYg6tbr__eHu9vDZvtt_cg',
    appId: '1:693235219914:web:805644e2892d000cd7e333',
    messagingSenderId: '693235219914',
    projectId: 'dars66-430ad',
    authDomain: 'dars66-430ad.firebaseapp.com',
    storageBucket: 'dars66-430ad.appspot.com',
    measurementId: 'G-04KQTSF8EJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyADd5C1DZ65tZe3fAOXpruajtQlLnqiIAs',
    appId: '1:693235219914:android:abbd779091a040d7d7e333',
    messagingSenderId: '693235219914',
    projectId: 'dars66-430ad',
    storageBucket: 'dars66-430ad.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCzAlzCPb3e_qLptBX1bxh0szI9p_4XxZo',
    appId: '1:693235219914:ios:489134eaf28e25c5d7e333',
    messagingSenderId: '693235219914',
    projectId: 'dars66-430ad',
    storageBucket: 'dars66-430ad.appspot.com',
    iosBundleId: 'com.example.dars66',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCzAlzCPb3e_qLptBX1bxh0szI9p_4XxZo',
    appId: '1:693235219914:ios:489134eaf28e25c5d7e333',
    messagingSenderId: '693235219914',
    projectId: 'dars66-430ad',
    storageBucket: 'dars66-430ad.appspot.com',
    iosBundleId: 'com.example.dars66',
  );
}
